import { CF_DOMAIN } from "../utils/consts";

interface Event {
  title: string;
  description: string;
  dates: string[];
  times: string[];
  locations: string[];
  spots?: string;
  image: string;
  link: string;
}

export const events: Event[] = [
  {
    title: "Delegate Training",
    description:
      "Never competed at Model UN conference before? Need a refresher on the flow of debate in crisis committees? Sign up for a Delegate Training session, hosted by our Co-ASGs of Hiring & Training, to learn all you need to know before participating in your first crisis committee!\n\n[Delegates must check in to the conference at OISE first before attending Delegate Training.]\n\n[Note:] Delegates are only permitted to attend {one} of the two sessions.",
    dates: ["Friday, October 24", "Friday, October 24"],
    times: ["1:00 – 2:00 PM", "3:00 – 4:00 PM"],
    locations: ["MS 2170", "MS 2170"],
    spots: "In Person: 280 (140 per session), Online: Unlimited",
    image: `${CF_DOMAIN}/DelegateTraining.JPG?format=webp`,
    link: "https://docs.google.com/forms/d/e/1FAIpQLSdL4hvJuvKMe3Go06UGxOhCunXApg6srVDFpwFmBAIMIpLxJg/viewform?usp=header",
  },
  {
    title: "Legislative Assembly Tour",
    description:
      "Join us for a free tour of the Legislative Assembly of Ontario at Queen’s Park! Discover the building's history and architecture, and learn about the traditions and function of Parliament. \n\n[Delegates must check in to the conference and meet at OISE first before attending the Legislative Assembly Tour. We will be leaving at 9:30 AM sharp!]",
    dates: ["Friday, October 24"],
    times: ["9:30 – 11:00 AM"],
    locations: ["OISE 8200"],
    spots: "35",
    image: `${CF_DOMAIN}/LegislativeAssemblyTours.jpg?format=webp`,
    link: "https://docs.google.com/forms/d/e/1FAIpQLSfp3zMulrxqlxRGFErmU6uVP6wOVNzano6un0_I6DbD9Pw29Q/viewform",
  },
  {
    title: "Charity Photoshoot",
    description:
      "For just a small donation to charity, get your own professional headshot or a group photo with your friends at University College, a historic Romanesque Revival-style building at the University of Toronto. Sign up for a slot today before spots fill up!\n\n[Note:] Costs for individual photos are different from group photos; please see the first page of the sign-up form for more information.\n\n[Delegates must check in to the conference at OISE first before attending the Charity Photoshoot.]",
    dates: ["Friday, October 24", "Saturday, October 25", "Sunday, October 26"],
    times: ["2:00 – 3:00 PM", "12:00 – 1:30 PM", "12:00 – 1:30 PM"],
    locations: ["UC 255", "UC 255", "UC 255"],
    spots: "240 (10 per 10-minute slot)",
    image: `${CF_DOMAIN}/CharityPhotoshoot.JPG?format=webp`,
    link: "https://docs.google.com/forms/d/e/1FAIpQLSendroJs6xX0WKW25DGxuwczpSofUyOwszep-_Ri2V1GuGVkQ/viewform",
  },
  {
    title: "Midnight Crisis",
    description:
      "Looking for another crisis committee to participate in? Can’t get enough of the crisis committees at SSICSIM? Sign up for (Midnight Crisis), a short but sweet committee directed by the Secretariat in the late hours of the first conference day! This year’s Midnight Crisis is ad hoc, so the committee topic will be revealed at the beginning of the session. ",
    dates: ["Friday, October 24"],
    times: ["8:00 – 11:00 PM"],
    locations: ["OI 2295"],
    spots: "20",
    image: `${CF_DOMAIN}/MidnightCrisis.jpg?format=webp`,
    link: "https://docs.google.com/forms/d/e/1FAIpQLSdVUzu9bIN6aSXWs6ANbv3SqgZjhxtmj3hkdsOqLSahnfP2nQ/viewform",
  },
  {
    title: "Delegate Social",
    description:
      "Looking to unwind after a long day of formal debate? Hoping to connect with other Delegates, Staff, and Secretariat members at SSICSIM? Sign up for Delegate Social, a lively event we’ll be hosting in the heart of the University of Toronto! [Free refreshments and dinner will be provided.]",
    dates: ["Saturday, October 25"],
    times: ["7:30 – 11:00 PM"],
    locations: ["St. Michael’s College (Father Madden Hall)"],
    spots: "120",
    image: `${CF_DOMAIN}/DelegateSocial.JPG?format=webp`,
    link: "https://forms.gle/LKUUnKbYrepvxMiF7",
  },
];

export const committeesData = [
  {
    title: "Fall of the Qing: Five Coloured Banners Over Jing",
    description: "",
    expandedDescription: "",
    backgroundGuides: [],
    contactEmail: "",
    director: "Chance Hattrick & Glenn Yu",
    directorImage: "",
    category: "Historical",
    backgroundImage: "",
    jointOrNot: false,
    double: false,
  },
  {
    title: "The Fall of the Old Kingdom",
    description: "",
    expandedDescription: "",
    backgroundGuides: [],
    contactEmail: "",
    director: "Wajid Zaman & Paula Chu",
    directorImage: "",
    category: "Historical",
    backgroundImage: "",
    jointOrNot: false,
    double: false,
  },
  {
    title: "Forged in Flames: The Franco-Prussian War",
    description: "",
    expandedDescription: "",
    backgroundGuides: [],
    contactEmail: "",
    director: "Aryan Rajagopal & Joshua Qu",
    directorImage: "",
    category: "Historical",
    backgroundImage: "",
    jointOrNot: true,
    double: false,
  },
  {
    title: "The Rovereta Affair, 1957",
    description: "",
    expandedDescription: "",
    backgroundGuides: [],
    contactEmail: "",
    director: "Ngila Stone & Luca Rampersad",
    directorImage: "",
    category: "Historical",
    backgroundImage: "",
    jointOrNot: true,
    double: false,
  },
  {
    title: "Historical Ad Hoc",
    description: "",
    expandedDescription: "",
    backgroundGuides: [],
    contactEmail: "",
    director: "Alexander Boldis",
    directorImage: "",
    category: "Historical",
    backgroundImage: "",
    jointOrNot: false,
    double: false,
  },
  {
    title: "Lord of the Rings: The Shattered Fellowship",
    description: "",
    expandedDescription: "",
    backgroundGuides: [],
    contactEmail: "",
    director: "Samantha Chang & Hasnain Heryani",
    directorImage: "",
    category: "Fictional",
    backgroundImage: "",
    jointOrNot: false,
    double: false,
  },
  {
    title: "Death Note (2006, Japan)",
    description: "",
    expandedDescription: "",
    backgroundGuides: [],
    contactEmail: "",
    director: "Sukaina Syed",
    directorImage: "",
    category: "Fictional",
    backgroundImage: "",
    jointOrNot: false,
    double: false,
  },
  {
    title: "The Meteor of Extinction: Pokemon Omega Ruby Alpha Sapphire",
    description: "",
    expandedDescription: "",
    backgroundGuides: [],
    contactEmail: "",
    director: "Annabelle Chin",
    directorImage: "",
    category: "Fictional",
    backgroundImage: "",
    jointOrNot: false,
    double: false,
  },
  {
    title: "A Wizarding Puzzle",
    description: "",
    expandedDescription: "",
    backgroundGuides: [],
    contactEmail: "",
    director: "Renzo Ugarte Basurco & Maria Aponiuk Sawicz",
    directorImage: "",
    category: "Fictional",
    backgroundImage: "",
    jointOrNot: true,
    double: false,
  },
  {
    title: "Fictional Ad Hoc",
    description: "",
    expandedDescription: "",
    backgroundGuides: [],
    contactEmail: "",
    director: "Jordan Bickramsingh",
    directorImage: "",
    category: "Fictional",
    backgroundImage: "",
    jointOrNot: false,
    double: false,
  },
  {
    title: "Marshal, Carter & Dark: The Firm",
    description: "",
    expandedDescription: "",
    backgroundGuides: [],
    contactEmail: "",
    director: "Evelyn So",
    directorImage: "",
    category: "Conceptual",
    backgroundImage: "",
    jointOrNot: false,
    double: false,
  },
  {
    title: "Rising Idols: Fame is a Weapon",
    description: "",
    expandedDescription: "",
    backgroundGuides: [],
    contactEmail: "",
    director: "Akshaya Churesh",
    directorImage: "",
    category: "Conceptual",
    backgroundImage: "",
    jointOrNot: false,
    double: false,
  },
  {
    title: "Family Ties: The Titanomachy",
    description: "",
    expandedDescription: "",
    backgroundGuides: [],
    contactEmail: "",
    director: "Lily Cohen",
    directorImage: "",
    category: "Conceptual",
    backgroundImage: "",
    jointOrNot: false,
    double: false,
  },
  {
    title: "Digital Gold Rush",
    description: "",
    expandedDescription: "",
    backgroundGuides: [],
    contactEmail: "",
    director: "Eileen Jones",
    directorImage: "",
    category: "Conceptual",
    backgroundImage: "",
    jointOrNot: false,
    double: false,
  },
  {
    title: "The Obedience Project",
    description: "",
    expandedDescription: "",
    backgroundGuides: [],
    contactEmail: "",
    director: "Beatrix Stone & Oscar Hollingsworth",
    directorImage: "",
    category: "Conceptual",
    backgroundImage: "",
    jointOrNot: true,
    double: false,
  },
  {
    title: "Conceptual Ad Hoc",
    description: "",
    expandedDescription: "",
    backgroundGuides: [],
    contactEmail: "",
    director: "???",
    directorImage: "",
    category: "Conceptual",
    backgroundImage: "",
    jointOrNot: false,
    double: false,
  },
];

export const scheduleData = [
  {
    day: "Friday, September 26",
    sessions: [
      {
        time: "5:00 PM – 6:00 PM",
        title: "Opening Ceremony",
        location: "Main Hall",
      },
      {
        time: "6:15 PM – 8:00 PM",
        title: "Committee Session I",
        location: "Assigned Rooms",
      },
    ],
  },
  {
    day: "Saturday, September 27",
    sessions: [
      {
        time: "9:00 AM – 12:00 PM",
        title: "Committee Session II",
        location: "Assigned Rooms",
      },
      {
        time: "1:00 PM – 4:00 PM",
        title: "Committee Session III",
        location: "Assigned Rooms",
      },
      {
        time: "7:00 PM – 10:00 PM",
        title: "Delegate Social",
        location: "Atrium",
      },
    ],
  },
  {
    day: "Sunday, September 28",
    sessions: [
      {
        time: "9:00 AM – 12:00 PM",
        title: "Committee Session IV",
        location: "Assigned Rooms",
      },
      {
        time: "1:00 PM – 2:00 PM",
        title: "Closing Ceremony",
        location: "Main Hall",
      },
    ],
  },
];

export const resources = [
  {
    title: "Rules of Procedures",
    description: "Understand the rules and procedures for the conference.",
    href: "https://drive.google.com/file/d/1CPD-I1XtxcrSHqEyWHYlxXyDsHF5X00G/view?usp=sharing",
    bg: `${CF_DOMAIN}/rop.jpeg?format=webp`, // example placeholder
  },
  {
    title: "Delegate's Guide to Crisis MUN",
    description:
      "A comprehensive guide for delegates participating in Crisis MUN.",
    href: "https://drive.google.com/file/d/18UHASiviwqNX4SCHptRfz_2rLLJbJPe1/view",
    bg: `${CF_DOMAIN}/delegates-guide.jpeg?format=webp`,
  },
  {
    title: "Committee Archives",
    description: "Explore past committee topics and materials.",
    href: "https://docs.google.com/document/d/1rj6pCLqc5eRTqLvVRy-XHe31KqZ1gckAcjwZpHCj9Wc/edit?usp=sharing",
    bg: `${CF_DOMAIN}/archive.jpg?format=webp`,
  },
];

export const secretariat = [
  {
    name: "Nazaha Fazil",
    position: "Secretary-General",
    image: `${CF_DOMAIN}/nazaha.jpg?format=webp`,
    branch: "Executive Board",
  },
  {
    name: "Leora Kasneci",
    position: "Deputy Secretary-General, Equity",
    image: `${CF_DOMAIN}/leora.png?format=webp`,
    branch: "Executive Board",
  },
  {
    name: "Ethan Currie",
    position: "USG External",
    image: `${CF_DOMAIN}/ethan.jpg?format=webp`,
    branch: "Executive Board",
  },
  {
    name: "Connor Begg",
    position: "USG Internal",
    image: `${CF_DOMAIN}/connor.jpg`,
    branch: "Executive Board",
  },
  {
    name: "Elisha Yao",
    position: "USG Academics",
    image: `${CF_DOMAIN}/elisha.png?format=webp`,
    branch: "Executive Board",
  },
  {
    name: "Wilson Wong",
    position: "Chargé D’Affaires",
    image: `${CF_DOMAIN}/wilson.jpg?format=webp`,
    branch: "External & Internal",
  },
  {
    name: "Shreya Aggarwal",
    position: "ASG Corporate Relations",
    image: `${CF_DOMAIN}/shreya.jpg?format=webp`,
    branch: "External & Internal",
  },
  {
    name: "Rafael Garcia Rosas",
    position: "ASG Logistics",
    image: `${CF_DOMAIN}/rafael.jpg?format=webp`,
    branch: "External & Internal",
  },
  {
    name: "Nicholas Ali",
    position: "Co-ASG Hiring & Training",
    image: `${CF_DOMAIN}/nicholas.jpg?format=webp`,
    branch: "Academics & Equity",
  },
  {
    name: "Alishba Noman",
    position: "Co-ASG Hiring & Training",
    image: `${CF_DOMAIN}/alishba.jpg?format=webp`,
    branch: "Academics & Equity",
  },
  {
    name: "Biew Biew Sakulwannadee",
    position: "Co-ASG Design & IT",
    image: `${CF_DOMAIN}/biewbiew.jpg`,
    branch: "External & Internal",
  },
  {
    name: "Ankur Phadke",
    position: "Co-ASG Design & IT",
    image: `${CF_DOMAIN}/ankur.jpg?format=webp`,
    branch: "External & Internal",
  },
  {
    name: "Pavithra Venkitaraman",
    position: "ASG Communications",
    image: `${CF_DOMAIN}/pavithra.jpg`,
    branch: "External & Internal",
  },
  {
    name: "Aryan Rajagopal",
    position: "ASG Historical Crises",
    image: `${CF_DOMAIN}/aryan.jpg?format=webp`,
    branch: "Academics & Equity",
  },
  {
    name: "Jeeya Kaur",
    position: "ASG Fictional Crises",
    image: `${CF_DOMAIN}/jay.jpg`,
    branch: "Academics & Equity",
  },
  {
    name: "Pavel Telega",
    position: "ASG Conceptual Crises",
    image: `${CF_DOMAIN}/pavel.jpg`,
    branch: "Academics & Equity",
  },
  {
    name: "Brian Daniel",
    position: "ASG Equity",
    image: `${CF_DOMAIN}/brian.jpg`,
    branch: "Academics & Equity",
  },
];
